### ISSUE TITLE
Add routing with TanStack Router

### ISSUE THREAD

**Issue by LuanRoger** [LuanRoger/electron-shadcn#50]
## Motivation

A router allow the apps have multi-page to navigate between them. Since many desktop apps have multiple pages, it's very important to the template offers a default router, so the developer can build a more dynamic app with multi-page support out of the box.

### Why TanStack Router?

The TanStack Router is a very feature rich router, covering a huge amount of edge cases. But for this template in specific, the router offers:

- 100% inferred TypeScript support
- Typesafe navigation
- Designed for client-side data caches (TanStack Query, SWR, etc.)

It's has a very good integration with the stack already being used by the template.

## TODO

To have a good implementation, here is the minimum requirements.

- [ ] Install the TanStack Router.
- [ ] Integrate with React.
- [ ] Create a opinionated structure to be easy to add new routes and pages.
- [ ] Refactor the implementation.

**Comment by MehekFatima** [comment]
Hi! I would like to contribute to this issue.

**Comment by LuanRoger** [comment]
Hello @MehekFatima.

Go ahead, I'll assign this issue to you. Good luck.

**Comment by MehekFatima** [comment]
Hi @LuanRoger,
I’ve submitted a pull request that addresses the issue with PR #59 . Could you kindly review it when you have a moment? Please let me know if any adjustments or further changes are needed. Thank you
