### ISSUE TITLE
Add vite-plugin-compression for asset compression in production builds

### ISSUE THREAD

**Issue by karthic-keyan** [LuanRoger/electron-shadcn#53]
### Summary

To improve the performance of our Electron-based project, we should add the [`vite-plugin-compression`](https://www.npmjs.com/package/vite-plugin-compression) plugin to compress static assets (JavaScript, CSS, etc.) during production builds.

This will help reduce the size of the assets sent to clients, improving load times and overall performance.

### Tasks

1. Install `vite-plugin-compression` as a dev dependency:
    ```bash
    npm install vite-plugin-compression --save-dev
    ```

2. Configure the plugin in `vite.config.ts`:
    ```ts
    import viteCompression from 'vite-plugin-compression';

    export default defineConfig({
      plugins: [
        viteCompression({
          algorithm: 'brotliCompress',  // You can choose 'gzip' as well
          ext: '.br',                   // or '.gz' for gzip
          threshold: 10240,             // Compress files larger than 10kb
          deleteOriginFile: false       // Keep original uncompressed files
        })
      ]
    });
    ```

3. Update the `README.md` to include information about `vite-plugin-compression` and how it's used to compress assets.

4. Test the build process by running:
    ```bash
    npm run build
    ```

5. Ensure that compressed files (`.br` or `.gz`) are created in the `dist` folder.

### Acceptance Criteria

- [ ] `vite-plugin-compression` is installed as a dev dependency.
- [ ] `vite.config.ts` is updated to include compression for production builds.
- [ ] Documentation in `README.md` is updated.
- [ ] Successful build with compressed assets.
